// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: textile.proto

package textile

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Textile_CreateTechnicalModel_FullMethodName = "/hestia.v1.textile.Textile/CreateTechnicalModel"
)

// TextileClient is the client API for Textile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextileClient interface {
	CreateTechnicalModel(ctx context.Context, in *TechnicalModel, opts ...grpc.CallOption) (*TechnicalModel, error)
}

type textileClient struct {
	cc grpc.ClientConnInterface
}

func NewTextileClient(cc grpc.ClientConnInterface) TextileClient {
	return &textileClient{cc}
}

func (c *textileClient) CreateTechnicalModel(ctx context.Context, in *TechnicalModel, opts ...grpc.CallOption) (*TechnicalModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TechnicalModel)
	err := c.cc.Invoke(ctx, Textile_CreateTechnicalModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextileServer is the server API for Textile service.
// All implementations must embed UnimplementedTextileServer
// for forward compatibility.
type TextileServer interface {
	CreateTechnicalModel(context.Context, *TechnicalModel) (*TechnicalModel, error)
	mustEmbedUnimplementedTextileServer()
}

// UnimplementedTextileServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTextileServer struct{}

func (UnimplementedTextileServer) CreateTechnicalModel(context.Context, *TechnicalModel) (*TechnicalModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTechnicalModel not implemented")
}
func (UnimplementedTextileServer) mustEmbedUnimplementedTextileServer() {}
func (UnimplementedTextileServer) testEmbeddedByValue()                 {}

// UnsafeTextileServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextileServer will
// result in compilation errors.
type UnsafeTextileServer interface {
	mustEmbedUnimplementedTextileServer()
}

func RegisterTextileServer(s grpc.ServiceRegistrar, srv TextileServer) {
	// If the following call pancis, it indicates UnimplementedTextileServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Textile_ServiceDesc, srv)
}

func _Textile_CreateTechnicalModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TechnicalModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextileServer).CreateTechnicalModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Textile_CreateTechnicalModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextileServer).CreateTechnicalModel(ctx, req.(*TechnicalModel))
	}
	return interceptor(ctx, in, info, handler)
}

// Textile_ServiceDesc is the grpc.ServiceDesc for Textile service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Textile_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hestia.v1.textile.Textile",
	HandlerType: (*TextileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTechnicalModel",
			Handler:    _Textile_CreateTechnicalModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "textile.proto",
}
