// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: accounting.proto

package accounting

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tax_GetVatRates_FullMethodName      = "/hestia.v1.accounting.Tax/GetVatRates"
	Tax_GetVatExemptions_FullMethodName = "/hestia.v1.accounting.Tax/GetVatExemptions"
)

// TaxClient is the client API for Tax service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaxClient interface {
	GetVatRates(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VatRates, error)
	GetVatExemptions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VatExemptions, error)
}

type taxClient struct {
	cc grpc.ClientConnInterface
}

func NewTaxClient(cc grpc.ClientConnInterface) TaxClient {
	return &taxClient{cc}
}

func (c *taxClient) GetVatRates(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VatRates, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VatRates)
	err := c.cc.Invoke(ctx, Tax_GetVatRates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxClient) GetVatExemptions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VatExemptions, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VatExemptions)
	err := c.cc.Invoke(ctx, Tax_GetVatExemptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaxServer is the server API for Tax service.
// All implementations must embed UnimplementedTaxServer
// for forward compatibility.
type TaxServer interface {
	GetVatRates(context.Context, *emptypb.Empty) (*VatRates, error)
	GetVatExemptions(context.Context, *emptypb.Empty) (*VatExemptions, error)
	mustEmbedUnimplementedTaxServer()
}

// UnimplementedTaxServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaxServer struct{}

func (UnimplementedTaxServer) GetVatRates(context.Context, *emptypb.Empty) (*VatRates, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVatRates not implemented")
}
func (UnimplementedTaxServer) GetVatExemptions(context.Context, *emptypb.Empty) (*VatExemptions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVatExemptions not implemented")
}
func (UnimplementedTaxServer) mustEmbedUnimplementedTaxServer() {}
func (UnimplementedTaxServer) testEmbeddedByValue()             {}

// UnsafeTaxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaxServer will
// result in compilation errors.
type UnsafeTaxServer interface {
	mustEmbedUnimplementedTaxServer()
}

func RegisterTaxServer(s grpc.ServiceRegistrar, srv TaxServer) {
	// If the following call pancis, it indicates UnimplementedTaxServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tax_ServiceDesc, srv)
}

func _Tax_GetVatRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxServer).GetVatRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tax_GetVatRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxServer).GetVatRates(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tax_GetVatExemptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxServer).GetVatExemptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tax_GetVatExemptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxServer).GetVatExemptions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Tax_ServiceDesc is the grpc.ServiceDesc for Tax service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tax_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hestia.v1.accounting.Tax",
	HandlerType: (*TaxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVatRates",
			Handler:    _Tax_GetVatRates_Handler,
		},
		{
			MethodName: "GetVatExemptions",
			Handler:    _Tax_GetVatExemptions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounting.proto",
}
