/**
 * @fileoverview gRPC-Web generated client stub for hestia.v1.textile
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.0
// source: textile.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as textile_pb from './textile_pb'; // proto import: "textile.proto"


export class TextileClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateTechnicalModel = new grpcWeb.MethodDescriptor(
    '/hestia.v1.textile.Textile/CreateTechnicalModel',
    grpcWeb.MethodType.UNARY,
    textile_pb.TechnicalModel,
    textile_pb.TechnicalModel,
    (request: textile_pb.TechnicalModel) => {
      return request.serializeBinary();
    },
    textile_pb.TechnicalModel.deserializeBinary
  );

  createTechnicalModel(
    request: textile_pb.TechnicalModel,
    metadata?: grpcWeb.Metadata | null): Promise<textile_pb.TechnicalModel>;

  createTechnicalModel(
    request: textile_pb.TechnicalModel,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: textile_pb.TechnicalModel) => void): grpcWeb.ClientReadableStream<textile_pb.TechnicalModel>;

  createTechnicalModel(
    request: textile_pb.TechnicalModel,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: textile_pb.TechnicalModel) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/hestia.v1.textile.Textile/CreateTechnicalModel',
        request,
        metadata || {},
        this.methodDescriptorCreateTechnicalModel,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/hestia.v1.textile.Textile/CreateTechnicalModel',
    request,
    metadata || {},
    this.methodDescriptorCreateTechnicalModel);
  }

}

