FROM golang:1.23

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy all the source code, including the subdirectories, but only the .go files
COPY . ./

# Command to run the tests
CMD ["go", "test", "-v", "./..."]