name: Docs CI
on:
  push:
    branches: ["main", "develop"]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      # If the branch is develop, deploy to /develop
      - if: github.ref == 'refs/heads/develop'
        run: mkdocs gh-deploy --config-file mkdocs.yml --remote-branch develop -d develop --force
      - if: github.ref == 'refs/heads/main'
        run: mkdocs gh-deploy --config-file mkdocs.yml --remote-branch main --force
