# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: API CI

on:
  push:
    branches: [ "main", "develop", "feature/*" ]
    paths:
      - 'api/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        
    - name: Build all packages
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
    - uses: actions/checkout@v4

    - name: Print the current directory
      run: pwd && ls -la

    - name: Start Docker CI with DB
      # Start the containers and exit when the tests end.
      working-directory: ./api
      run: docker compose --profile test up --abort-on-container-exit